#!/bin/bash
module load  some/modules/for/qe 
export OMP_NUM_THREADS=8
echo $OMP_NUM_THREADS

echo " Done."

echo started at "$(date)"

#rm -rf  tmp FILD3DYN

bin="path/to/qe/bin"
pref="mpirun -np 12 "  # e.g. "mpirun -np 4 "
post="-npool 4 "  # e.g. -npool 4

echo "d3 calculation"
$pref $bin/d3q.x -in d3.in > d3.out

echo "computing 3-body force constants"
ls FILD3DYN/anh* | $bin/d3_qq2rr.x -c 4 3 3 3 > d3_qq2rr.out

echo "computing 3-body force constants recentered "
ls FILD3DYN/anh* | $bin/d3_qq2rr.x -c 4 3 3 3 -f 0 -o FORCE_CONSTANTS_3RD > kaldo_3ifc.out

echo "appying sum rules 3-body force constants"
$pref $bin/d3_asr3.x -i FORCE_CONSTANTS_3RD -o FORCE_CONSTANTS_3RD.asr -t 1.e-12 -n 10000 -p 2 -m > d3_asr3.out



# uncomment to test kaldo results vs d3q ones
#echo "appying sum rules 3-body force constants"
#$pref $bin/d3_asr3.x -i mat3R -o mat3R.asr -t 1.e-12 -n 10000 -p 2 > d3_asr3.out

#echo "preparing sparse representation of 3-body force constants"
#$pref $bin/d3_sparse.x -i mat3R.asr -o mat3R.asr.sparse -t 0. -n 10000 > d3_sparse.out

#echo "doing linewidth dispersion calculation"
#$pref $bin/d3_lw.x -in input.LW > output.LW
#gnuplot -persist plot-lw.gp

#echo "doing SMA thermal conductivity calculation"
#$pref $bin/d3_tk.x -in input.TK-sma > output.TK-sma



echo finished at "$(date)"
echo " Done."

