# force constants generated by Mattersim with LAMMPS
from ase.io import read
from kaldo.conductivity import Conductivity
from kaldo.forceconstants import ForceConstants
from kaldo.phonons import Phonons
import kaldo.controllers.plotter as plotter
import numpy as np

# Denote supercell size for second fc and root folder

### Set up force constant objects via interface to LAMMPS ####

# Replicate the unit cell 'nrep'=1 time
nrep = 1
supercell = np.array([nrep, nrep, nrep])

# Load in computed 2nd, 3rd IFCs from LAMMPS outputs
forceconstants = ForceConstants.from_folder(folder='fc_aSi512',supercell=supercell,format='lammps')


# Establish the temperature array
temperatures = np.arange(10, 1060, 50, dtype=int)
kappa_values = []

for temperature in temperatures:

    phonons_config = {'is_classic': False,
                  'temperature': temperature,
                  'folder': 'ALD_aSi512',
                   'third_bandwidth':0.5/4.135, # 0.5 eV is used here.
                   'broadening_shape':'triangle',
                    'storage': 'numpy'}

    phonons = Phonons(forceconstants=forceconstants, **phonons_config)
 
    print('\n')
    qhgk_cond_matrix = Conductivity(phonons=phonons, method='qhgk', n_iterations=0).conductivity.sum(axis=0)
    print('Thermal conductivity QHGK (W/mK): %.3f'%(np.mean(np.diag(qhgk_cond_matrix))))
    print(qhgk_cond_matrix)

    kappa = qhgk_cond_matrix.trace() / 3.0
    kappa_values.append(kappa)

# Convert list to array
kappa_values = np.array(kappa_values)

# Stack numpy array
np.savetxt('kappa_vs_T_a-Si.dat', np.vstack([temperatures, kappa_values]).T)
