# Example: germanium bulk 
# Computes: anharmonic properties and thermal conductivity for germanium bulk (2 atoms per cell)
# force constants generated by d3q

from kaldo.conductivity import Conductivity
from kaldo.forceconstants import ForceConstants
from kaldo.phonons import Phonons
import kaldo.controllers.plotter as plotter
import numpy as np
import os
import tarfile

# Denote supercell size for seocnd fc and root folder
ini_sc=[9,9,9]
root='./fc_DFT/'

### Set up forceconstants object
# possible different supercell for second and third
forceconstants = ForceConstants.from_folder(root,supercell=ini_sc,third_supercell=np.array([5,5,5]),format='shengbte-d3q')

### Set up the phonon object and the anharmonic properties calculations ####

# Configure phonon object
# 'k_points': number of k-points
# 'is_classic': specify if the system is classic, True for classical and False for quantum
# 'temperature: temperature (Kelvin) at which simulation is performed
# 'folder': name of folder containing phonon property and thermal conductivity calculations
# 'storage': Format to storage phonon properties ('formatted' for ASCII format data, 'numpy' 
#            for python numpy array and 'memory' for quick calculations, no data stored)

# Define the k-point mesh using 'kpts' parameter
k_points = 15 # k points in each direction
temperature = 300

phonons_config = {'kpts': [k_points, k_points, k_points],
                  'is_classic': False, 
                  'temperature': temperature, #'temperature'=300K
                  'folder': 'ALD',
                  'is_unfolding':True,
		  'storage': 'numpy'}

# Set up phonon object by passing in configuration details and the forceconstants object computed above
phonons = Phonons(forceconstants=forceconstants, **phonons_config)

# Plot phonon dispersion
plotter.plot_dispersion(phonons,n_k_points=200)
plotter.plot_dos(phonons,p_atoms=None, bandwidth=0.005, filename='dos')

### Set up the Conductivity object and thermal conductivity calculations ####

# Compute thermal conductivity (t.c.) by solving Boltzmann Transport
# Equation (BTE) with various of methods

# 'phonons': phonon object obtained from the above calculations
# 'method': specify methods to solve for BTE  
# ('rta' for RTA,'sc' for self-consistent and 'inverse' for direct inversion of the scattering matrix)
# Calculate conductivity with direct inversion approach (inverse)
print('\n')
inv_cond_matrix = (Conductivity(phonons=phonons, method='inverse').conductivity.sum(axis=0))
print('Bulk thermal conductivity (W/m/K): ', np.mean([inv_cond_matrix[0,0], inv_cond_matrix[1,1], inv_cond_matrix[2,2]]))
print('\n')
print('Thermal condutivity tensor: \n')
print(inv_cond_matrix)


# Trun on include_isotopes in phonon object
phonons.include_isotopes = True

inv_cond_matrix_iso = (Conductivity(phonons=phonons, method='inverse').conductivity.sum(axis=0))
print('Bulk thermal conductivity with iso(W/m/K): ', np.mean([inv_cond_matrix_iso[0,0], inv_cond_matrix_iso[1,1], inv_cond_matrix_iso[2,2]]))
print('\n')
print('Thermal condutivity tensor wit iso: \n')
print(inv_cond_matrix_iso)
print('\n')
